twig:
    file_name_pattern: '*.twig'
    default_path: '%kernel.project_dir%/templates'

    globals:
        site_name: 'MTU asbl'
        site_description: 'Mwanadamu Tumaini - Paix et développement au Sud-Kivu'